### ISSUE TITLE
`--debug` option

### ISSUE THREAD

**Issue by Schwad** [scarpe-team/scarpe#104]
It would be nice to support a `--debug` option to turn on all of our `do_debug` logs on the CLI level, although this can currently be set explicitly in the Ruby code right now.

**Comment by svijaysuriya** [comment]
could anyone provide some more context to this issue if this issue is still open?

**Comment by gintama91** [comment]
@svijaysuriya 
i will explain on basis of what i understand if anyone think its wrong point it out!
 basically we want debug = true when we do something like `./exe/scarpe examples/ayx.rb --debug`

**Comment by Akseluhreyter** [comment]
As per the discussion on [Discord](https://discord.com/channels/1072538177321058377/1072538178659024898/1101573861121736795), I'm bringing up the discussion here.

I'd like to implement this feature if there's still interest/makes sense. 

I do have some questions/concerns though. I don't get the debug output from the code in the above comment and I'm not entirely sure I'm suppose to? The `@debug` is set, but no additional output like above.

In order to make this change, my first approach involves changing two files. `exe/scrape` needs to be changed to handle parsing and setting the debug state. `lib/scarpe/app.rb` needs to have the `Scarpe::App` _class_ changed to have a debug accessor to set/get a corresponding _class instance var_. Instances of `Scarpe::App` can then pull the default state from the `Scarpe::App` class.

**_Alternatively_**, the ARGV processing could be moved into the Scarpe::App's #initialize. This would avoid creating new methods and instance vars on the class. However, this brings the cost of scattering the command line parsing across files and subclasses that implement their own #initialize would need to handle this, albeit light, parsing on their own.

There aren't many options being parsed as is. Two counting this (unimplemented) one. And it's unlikely Scarpe::App would be subclassed. So I think it's understandable if the latter approach is chosen.

I'm also curious how to handle the situation when the Shoes namespace is already defined. Line 21 of `exe/scarpe` is `Shoes = Scarpe unless defined?(Shoes)`. If ``Shoes`` is already defined for some reason, the debug flag may not be seen since Scarpe isn't used. Do these command line options need to worry about this situation?

**Comment by noahgibbs** [comment]
This is just waiting for #222 to be merged.

**Comment by noahgibbs** [comment]
Fixed.
