### ISSUE TITLE
[Future][Pie-in-the-sky] Bootstrap

### ISSUE THREAD

**Issue by Schwad** [scarpe-team/scarpe#105]
Documenting this context here quickly. One thing we talked about was having a "bootstrap" plugin or gem that, when run with scarpe, would give someone fancy stylings out of the box without setting margins and sizes and button stylings all on their own. Nifty, right?

**Comment by jean-francois-labbe** [comment]
It makes me think of https://simplecss.org/
> A CSS framework that makes semantic HTML look good.

**Comment by noahgibbs** [comment]
With the recent Calzini PR, this just got a lot easier. You should be able to create an HTML renderer matching the Calzini interface (maybe just by subclassing Calzini) and then drop it in as the renderer in a line or three in wv.rb.

**Comment by jean-francois-labbe** [comment]
@noahgibbs could you link the Calzini PR, I can't find it.

**Comment by noahgibbs** [comment]
https://github.com/scarpe-team/scarpe/pull/380

**Comment by noahgibbs** [comment]
Looks like this is going to require #253 as well, due to how Webview does CORS support. We'll need to support external files for e.g. bootstrap's CSS. And right now there's no good way to use an external file from our current page setup using a data URL and navigate. Or maybe we could convert the CSS file to a data URL? That sounds bad, though. Better to support local assets, which we'll need before long anyway.
