### ISSUE TITLE
[Future] Packaging

### ISSUE THREAD

**Issue by Schwad** [scarpe-team/scarpe#20]
Right now we're just aiming to have this run nicely locally on a mac with `ruby my_app.rb`. Long term it would be nice to replicate that full "build" packaging functionality where we could send this as a standalone package for mac, windows, linux to anyone even without ruby!

**Comment by Schwad** [comment]
Kind of what I'm thinking for [Future] is after we've passed all examples. Things like packaging, splash app, hackety hack, etc.

**Comment by noahgibbs** [comment]
Relevant: https://www.ruby-toolbox.com/categories/packaging_to_executables

Though it looks like a pretty moribund category. Travelling Ruby supports Ruby 2.4 at latest (EOL'd 3 years ago). Ruby-packer stops support at 2.7. Ocra is Windows-only. Ruby-ship is Ruby 2.3 or older. Rb2exe stops at Ruby 2.2. Rubinjam doesn't seem to be very mature, but *does* support up to Ruby 3.1. I think Releasy and Crate are dead. Rubyscript2exe was last released in 2007. 

Our best option might be Omnibus (https://github.com/chef/omnibus), which is Chef's fearsomely complex Ruby packager. I remember it being hugely painful when I tried a few years ago. It doesn't look a lot better now, based on docs, etc. There's a tutorial for it from Scout, but the blog post seems to be missing some of the code and their Git repo for it is archived.

But on the plus side, Omnibus appears reasonably up-to-date and maintained, and seems to support at *least* up to Ruby 3.1, possibly higher.

**Comment by noahgibbs** [comment]
Some additional (useful?) references...

Travelling Ruby isn't going to be updated by the original author/maintainer any time soon: https://www.joyfulbikeshedding.com/blog/2021-01-06-the-future-of-traveling-ruby.html

However, there's at least one other group using the work and updating it, including to Ruby 3.2.2: https://github.com/phusion/traveling-ruby/pull/133

And apparently the big obstacle to packaging is MacOS. They change things frequently, they don't have MacOS-in-Docker, SIP (System Integrity Protection) makes it hard to do a local build... See the first link for more details. While you don't need to do later MacOS packaging in MacOS, it looks like you *do* have to build Travelling Ruby on (inclusively) MacOS in order to get the correct MacOS files.

If we wanted to use Travelling Ruby here, we'd probably be looking at updating it, at least partly, for ourselves. Here's a somewhat-dated brain dump of what that would entail: https://github.com/phusion/traveling-ruby/issues/88

**Comment by Schwad** [comment]
Re: omnibus. I used to work at Chef so might be able to petition more guidance there as well!

**Comment by noahgibbs** [comment]
While we could get guidance, I'd prefer a different approach if we can get it. Omnibus is *not* easy to use, and I don't just mean because it's under-documented. Travelling Ruby is just doing something that's lighter-weight by nature.

**Comment by noahgibbs** [comment]
For far-future issues that nobody is working actively on, I think it makes a lot more sense to have a design wiki page instead of an issue so we can easily edit, rearrange, etc. the relevant notes. I've put packaging info into a wiki page instead of this issue: https://github.com/scarpe-team/scarpe/wiki/Packaging.md
