### ISSUE TITLE
Slot Pop Behavior When Only One Widget is Present

### ISSUE THREAD

**Issue by gintama91** [scarpe-team/scarpe#301]
pop_slot method pops the slot even when it contains only one widget..
 
 ```
 Shoes.app do
  @push = button "Push me"
  @push.click {
    puts " i am inside click what about slot?"
    para "Pushed!"
  }
end
```
this would give us this output
```
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
push_slot: #<Scarpe::DocumentRoot:0x00007f7c0b855640>
slot is now: [<Scarpe::DocumentRoot>]
current_slot: #<Scarpe::DocumentRoot:0x00007f7c0b855640>
parent: <Scarpe::DocumentRoot>
pop_slot: [<Scarpe::DocumentRoot>]
slot is now: []
 i am inside click what about slot?
current_slot: 
parent: nil
```

**Comment by gintama91** [comment]
for this i am not sure if its ok to do something like
```
    def pop_slot
      puts "pop_slot: #{@slots}"
      return if @slots.size <= 1
      @slots.pop
      puts "slot is now: #{@slots}"
    end
    ```
    
    but i am not sure if this would result in unexpected behaviour in other cases..?
    
    we can do something like clear current slot in destroy method ig after leaving a slot here

**Comment by noahgibbs** [comment]
Ah, got it. Since the DocumentRoot get popped, we don't have a slot when we're in a signal handler. I'd be fine with "don't pop if there's only one", sure -- that would mean if nothing's there, the default is the DocumentRoot. We could also literally make that the rule -- if there's no other current slot, return the DocumentRoot.

The only weird cases, which would be fine here, are:

* what if we add a whole stack/flow/shape/etc during a signal handler? That's fine, they'll push a slot (note: shape doesn't do this yet, but it will)
* what if we're in a Shoes::Widget, not the normal Shoes::App.new? We're going to have to write a bunch of new code for that case anyway, so don't need to worry about it yet

**Comment by noahgibbs** [comment]
Also, oh man, I guess that means we didn't have a test that adds widgets from a signal handler. That's not good. We should have a test that does that.

**Comment by noahgibbs** [comment]
I think this is fixed now. @gintama91, do you agree?

**Comment by gintama91** [comment]
i am closing this with just adding a note 
we didnt added any base rule like  if there's no other current slot, return the DocumentRoot.

we just not popping out if there is one element ig it would be documentroot this way too but yeah

**Comment by noahgibbs** [comment]
Yeah, because of when/how we push the DocumentRoot, those rules basically do the same thing.

We'll have to figure out how to handle an in-app Scarpe::Widget, but that's going to require some special-case code no matter what.
